# Generated by Django 3.2.11 on 2022-04-20 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_1', models.FloatField()),
                ('v_2', models.FloatField()),
                ('v_3', models.FloatField()),
                ('v_4', models.FloatField()),
                ('v_5', models.FloatField()),
                ('v_6', models.FloatField()),
                ('v_7', models.FloatField()),
                ('v_8', models.FloatField()),
                ('v_9', models.FloatField()),
                ('v_10', models.FloatField()),
                ('v_11', models.FloatField()),
                ('v_12', models.FloatField()),
                ('v_13', models.FloatField()),
                ('v_14', models.FloatField()),
                ('v_15', models.FloatField()),
                ('v_16', models.FloatField()),
                ('v_17', models.FloatField()),
                ('v_18', models.FloatField()),
                ('v_19', models.FloatField()),
                ('v_20', models.FloatField()),
                ('v_21', models.FloatField()),
                ('v_22', models.FloatField()),
                ('v_23', models.FloatField()),
                ('v_24', models.FloatField()),
                ('v_25', models.FloatField()),
                ('v_26', models.FloatField()),
                ('v_27', models.FloatField()),
                ('v_28', models.FloatField()),
                ('time', models.FloatField()),
                ('amount', models.FloatField()),
                ('prediction', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
            options={
                'db_table': 'predictions',
            },
        ),
    ]
