# Generated by Django 3.2.11 on 2022-11-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_profile_prediction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prediction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='prediction',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='time',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='v_1',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='v_10',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='v_11',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='v_12',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='v_13',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='v_14',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='v_15',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='v_16',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='v_17',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='v_18',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='v_19',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='v_2',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='v_20',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='v_21',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='v_22',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='v_23',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='v_24',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='v_25',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='v_26',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='v_27',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='v_28',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='v_3',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='v_4',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='v_5',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='v_6',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='v_7',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='v_8',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='v_9',
        ),
        migrations.AddField(
            model_name='prediction',
            name='amt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='cc_num',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='first',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='is_fraud',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='last',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='lat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='long',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='merch_lat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='merch_long',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='merchant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='trans_date_trans_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='trans_num',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='unix_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='zipcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
